const GET_ALL_GROUPS = 'GET_ALL_GROUPS';
const REMOVE_GROUP = 'REMOVE_GROUP';
const UPDATE_GROUP = 'UPDATE_GROUP';
const ADD_GROUP = 'ADD_GROUP';

const GET_ALL_ROBOTS = 'GET_ALL_ROBOTS';
const ADD_ROBOT = 'ADD_ROBOT';
const UPDATE_ROBOT = 'UPDATE_ROBOT';
const GET_BIND_ROBOTS = 'GET_BIND_ROBOTS';
const BIND_ROBOT = 'BIND_ROBOT';

const UPDATE_TOTAL_ITEMS = 'UPDATE_TOTAL_ITEMS';

const UPDATE_UUID = 'UPDATE_UUID';

const OPEN_SOCKET = 'OPEN_SOCKET';

const UPDATE_VIEW_GROUP_ID = 'UPDATE_VIEW_GROUP_ID';


export default {
  GET_ALL_GROUPS,
  REMOVE_GROUP,
  UPDATE_GROUP,
  GET_ALL_ROBOTS,
  ADD_GROUP,
  ADD_ROBOT,
  OPEN_SOCKET,
  UPDATE_ROBOT,
  GET_BIND_ROBOTS,
  UPDATE_VIEW_GROUP_ID,
  UPDATE_TOTAL_ITEMS,
  BIND_ROBOT,
  UPDATE_UUID
};